#pragma once

/// @file
/// umbrella header

#include "trs/core/cmp.h"
#include "trs/core/export.h"
#include "trs/core/hash.h"
#include "trs/core/print.h"
#include "trs/core/rng.h"
#include "trs/core/span.h"
#include "trs/core/status.h"
#include "trs/core/util.h"

#include "trs/alloc/aligned.h"
#include "trs/alloc/alloc.h"
#include "trs/alloc/arena.h"
#include "trs/alloc/default.h"
#include "trs/alloc/log.h"
#include "trs/alloc/pool.h"

#include "trs/algo/compare.h"
#include "trs/algo/copy.h"
#include "trs/algo/fill.h"
#include "trs/algo/fn.h"
#include "trs/algo/fold.h"
#include "trs/algo/heap.h"
#include "trs/algo/merge.h"
#include "trs/algo/modify.h"
#include "trs/algo/permute.h"
#include "trs/algo/search.h"
#include "trs/algo/set.h"
#include "trs/algo/sort.h"
#include "trs/algo/transform.h"

#include "trs/ds/arr.h"
#include "trs/ds/bitset.h"
#include "trs/ds/deque.h"
#include "trs/ds/hmap.h"
#include "trs/ds/hset.h"
#include "trs/ds/list.h"
#include "trs/ds/pqueue.h"
#include "trs/ds/queue.h"
#include "trs/ds/stack.h"
#include "trs/ds/vec.h"
